name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Static Site
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
